FROM eclipse-temurin:17-jdk

WORKDIR /app

COPY target/app.jar app.jar

EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-XX:+UseContainerSupport", "-XX:MaxRAMPercentage=75.0", "-jar", "/app/app.jar"]

