FROM openjdk:17-jdk-slim

WORKDIR /app

COPY target/autopilot-app.jar app.jar

EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-XX:+UseContainerSupport", "-XX:MaxRAMPercentage=75.0", "-jar", "/app/app.jar"]

